### ISSUE TITLE
It appears that "react-hot-loader/patch" did not run immediately

### ISSUE THREAD

**Issue by MariusAlch** [black-monolith/LightCycle#7]
After clone -> yarn -> npm start im getting error in console 

 "It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports."

I can see you moved "parts.hotModuleReplacement()," to the top probably for this reason, but I am still getting this error

PS. Awesome starter kit

**Comment by kube** [comment]
Thanks for creating the issue.

We are aware of this issue, but we're currently working on the upgrade to Webpack 2 and React Router 4 (That should also fix some other issues with HotReload).

Webpack configuration folder is being heavily modified, and once this done we'll fix this issue.

**P.S.** Thanks. It's cool to see people interested in our project, do not hesitate to give us feedback we appreciate it.
